/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  sidebar: [
    {
      type: 'link',
      label: 'Utils',
      href: '/docs/api/modules#functions',
    },
    {
      Providers: [
        'api/classes/JsonRpcProvider',
        'api/classes/FallthroughProvider',
      ],
    },
    {
      'Full API': [
        {
          type: 'autogenerated',
          dirName: 'api', // 'api' is the 'out' directory
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
