// autogenerated in "fetch-chains-info.ts"
// Do not edit directly
export default {
  "1": [
    "eth",
    "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
  ],
  "5": [
    "gor",
    "0x112234455c3a32fd11230c42e7bccd4a84e02010"
  ],
  "10": [
    "oeth"
  ],
  "50": [
    "xdc"
  ],
  "56": [
    "bnb"
  ],
  "100": [
    "gno"
  ],
  "137": [
    "matic"
  ],
  "250": [
    "ftm"
  ],
  "324": [
    "zksync"
  ],
  "1101": [
    "zkevm"
  ],
  "1337": [
    "geth"
  ],
  "7700": [
    "canto"
  ],
  "9001": [
    "evmos"
  ],
  "42161": [
    "arb1"
  ],
  "42220": [
    "celo"
  ],
  "43114": [
    "avax"
  ],
  "59140": [
    "linea-testnet"
  ],
  "80001": [
    "maticmum"
  ],
  "421613": [
    "arb-goerli"
  ],
  "534352": [
    "scr"
  ],
  "11155111": [
    "sep"
  ]
}