// autogenerated in "fetch-chains-info.ts"
// Do not edit directly
export default {
  "1": [
    "eth",
    "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
  ],
  "5": [
    "gor",
    "0x112234455c3a32fd11230c42e7bccd4a84e02010"
  ],
  "10": [
    "oeth"
  ],
  "14": [
    "flr"
  ],
  "16": [
    "cflr"
  ],
  "19": [
    "sgb"
  ],
  "25": [
    "cro"
  ],
  "40": [
    "TelosEVM"
  ],
  "41": [
    "TelosEVMTestnet"
  ],
  "50": [
    "xdc"
  ],
  "51": [
    "txdc"
  ],
  "56": [
    "bnb"
  ],
  "66": [
    "okt"
  ],
  "97": [
    "bnbt"
  ],
  "100": [
    "gno"
  ],
  "114": [
    "c2flr"
  ],
  "137": [
    "matic"
  ],
  "250": [
    "ftm"
  ],
  "280": [
    "zksync-goerli"
  ],
  "288": [
    "Boba"
  ],
  "314": [
    "filecoin"
  ],
  "324": [
    "zksync"
  ],
  "420": [
    "ogor"
  ],
  "599": [
    "metis-goerli"
  ],
  "841": [
    "tara"
  ],
  "842": [
    "taratest"
  ],
  "888": [
    "wan"
  ],
  "999": [
    "twan"
  ],
  "1038": [
    "bronos-testnet"
  ],
  "1039": [
    "bronos-mainnet"
  ],
  "1088": [
    "metis-andromeda"
  ],
  "1101": [
    "zkevm"
  ],
  "1284": [
    "mbeam"
  ],
  "1285": [
    "mriver"
  ],
  "1287": [
    "mbase"
  ],
  "1337": [
    "geth"
  ],
  "1442": [
    "testnet-zkEVM-mango"
  ],
  "2000": [
    "dc"
  ],
  "3141": [
    "filecoin-hyperspace"
  ],
  "3737": [
    "csb"
  ],
  "4002": [
    "tftm"
  ],
  "4242": [
    "nexi"
  ],
  "4689": [
    "iotex-mainnet"
  ],
  "4690": [
    "iotex-testnet"
  ],
  "7700": [
    "canto"
  ],
  "8082": [
    "Sphinx10"
  ],
  "8217": [
    "Cypress"
  ],
  "9000": [
    "evmos-testnet"
  ],
  "9001": [
    "evmos"
  ],
  "10200": [
    "chi"
  ],
  "31337": [
    "got"
  ],
  "42161": [
    "arb1"
  ],
  "42220": [
    "celo"
  ],
  "43113": [
    "Fuji"
  ],
  "43114": [
    "avax"
  ],
  "44787": [
    "ALFA"
  ],
  "53935": [
    "DFK"
  ],
  "80001": [
    "maticmum"
  ],
  "84531": [
    "basegor"
  ],
  "314159": [
    "filecoin-calibration"
  ],
  "421613": [
    "arb-goerli"
  ],
  "534353": [
    "scr-alpha"
  ],
  "1337803": [
    "zhejiang"
  ],
  "11155111": [
    "sep"
  ],
  "344106930": [
    "calypso-testnet"
  ],
  "503129905": [
    "nebula-staging"
  ],
  "1273227453": [
    "human-mainnet"
  ],
  "1313161554": [
    "aurora"
  ],
  "1313161555": [
    "aurora-testnet"
  ],
  "1351057110": [
    "chaos-tenet"
  ],
  "1482601649": [
    "nebula-mainnet"
  ],
  "1564830818": [
    "calypso-mainnet"
  ],
  "1666600000": [
    "hmy-s0"
  ],
  "2046399126": [
    "europa"
  ]
}